// Auto-generated by kysely-codegen — run `pnpm --filter @pos-system/api db:gen` to regenerate.
// Do not hand-edit this file.

import type { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely';

// ─── Table row types ──────────────────────────────────────────────────────────

export interface UsersTable {
  user_id: Generated<number>;
  name: string;
  username: string;
  password_hash: string;
  role: 'cashier' | 'chef' | 'admin';
  status: 'active' | 'inactive';
  created_at: ColumnType<Date, string | undefined, never>;
}

export interface RestaurantTablesTable {
  table_id: Generated<number>;
  table_number: number;
  capacity: number;
  status: 'available' | 'occupied';
}

export interface CategoriesTable {
  category_id: Generated<number>;
  name: string;
  description: string | null;
}

export interface MenuItemsTable {
  menu_item_id: Generated<number>;
  name: string;
  description: string | null;
  price: number;
  category_id: number;
  image_url: string | null;
  is_available: number; // tinyint(1)
}

export interface OrdersTable {
  order_id: Generated<number>;
  user_id: number;
  table_id: number | null;
  order_type: 'dine-in' | 'takeout';
  status: 'new' | 'preparing' | 'ready' | 'completed' | 'cancelled';
  total_amount: number;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, string | undefined, string | undefined>;
}

export interface OrderItemsTable {
  order_item_id: Generated<number>;
  order_id: number;
  menu_item_id: number;
  quantity: number;
  unit_price: number;
  subtotal: number;
  notes: string | null;
  status: 'pending' | 'preparing' | 'ready' | 'served';
}

export interface PaymentsTable {
  payment_id: Generated<number>;
  order_id: number;
  method: 'cash' | 'card' | 'online';
  amount: number;
  payment_status: 'pending' | 'completed' | 'refunded';
  transaction_ref: string | null;
  paid_at: ColumnType<Date, string | undefined, never>;
}

export interface InventoryTable {
  inventory_id: Generated<number>;
  menu_item_id: number;
  stock_qty: number;
  unit: string;
  min_stock: number;
  updated_at: ColumnType<Date, string | undefined, string | undefined>;
}

export interface OrderStatusLogTable {
  log_id: Generated<number>;
  order_id: number;
  status: 'new' | 'preparing' | 'ready' | 'completed' | 'cancelled';
  changed_by: number;
  changed_at: ColumnType<Date, string | undefined, never>;
}

// ─── Database interface ───────────────────────────────────────────────────────

export interface Database {
  users: UsersTable;
  restaurant_tables: RestaurantTablesTable;
  categories: CategoriesTable;
  menu_items: MenuItemsTable;
  orders: OrdersTable;
  order_items: OrderItemsTable;
  payments: PaymentsTable;
  inventory: InventoryTable;
  order_status_log: OrderStatusLogTable;
}

// ─── Selectable / Insertable / Updateable helpers ────────────────────────────

export type User = Selectable<UsersTable>;
export type NewUser = Insertable<UsersTable>;
export type UserUpdate = Updateable<UsersTable>;

export type RestaurantTable = Selectable<RestaurantTablesTable>;
export type NewRestaurantTable = Insertable<RestaurantTablesTable>;
export type RestaurantTableUpdate = Updateable<RestaurantTablesTable>;

export type Category = Selectable<CategoriesTable>;
export type NewCategory = Insertable<CategoriesTable>;
export type CategoryUpdate = Updateable<CategoriesTable>;

export type MenuItem = Selectable<MenuItemsTable>;
export type NewMenuItem = Insertable<MenuItemsTable>;
export type MenuItemUpdate = Updateable<MenuItemsTable>;

export type Order = Selectable<OrdersTable>;
export type NewOrder = Insertable<OrdersTable>;
export type OrderUpdate = Updateable<OrdersTable>;

export type OrderItem = Selectable<OrderItemsTable>;
export type NewOrderItem = Insertable<OrderItemsTable>;
export type OrderItemUpdate = Updateable<OrderItemsTable>;

export type Payment = Selectable<PaymentsTable>;
export type NewPayment = Insertable<PaymentsTable>;
export type PaymentUpdate = Updateable<PaymentsTable>;

export type Inventory = Selectable<InventoryTable>;
export type NewInventory = Insertable<InventoryTable>;
export type InventoryUpdate = Updateable<InventoryTable>;

export type OrderStatusLog = Selectable<OrderStatusLogTable>;
export type NewOrderStatusLog = Insertable<OrderStatusLogTable>;
